# With this docker-compose.yml, when you run docker-compose up, Docker will pull the PostgreSQL image
# (if not already present) and start a PostgreSQL container.

version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432"